/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatapplication.frames;

import chatapplication.rooms.RoomManager;
import javax.swing.DefaultListModel;

/**
 *
 * @author root
 */
public class RoomsFrame extends javax.swing.JInternalFrame {
    private RoomManager roomManager;
    /**
     * Creates new form RoomsFrame
     */
    public RoomsFrame() {
        initComponents();
        roomManager = new RoomManager();
        createRooms();
    }
    public void createRooms(){
        rooms.removeAll();
        rooms.setModel(createRoomList());
    }
    public DefaultListModel createRoomList(){
        DefaultListModel model = new DefaultListModel();
        for(int i=0;i<5;i++){
            model.addElement("room "+i);
        }
        for(int i=0;i<5;i++){
            roomManager.addRoom("room "+i);
        }
        return model;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        rooms = new javax.swing.JList<>();

        rooms.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        rooms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(rooms);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roomsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomsMouseClicked
        String room = rooms.getSelectedValue();
        RoomFrame roomFrame = new RoomFrame(roomManager.getRoomByName(room));
        setVisible(false);
    }//GEN-LAST:event_roomsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> rooms;
    // End of variables declaration//GEN-END:variables
}
